### ISSUE TITLE
Web-App revision 01

### ISSUE THREAD

**Issue by wickywaka** [SpotTroop/web-app#13]
![Image](https://user-images.githubusercontent.com/6962179/199222604-d255f79c-867e-4b4a-952f-165742fbbae3.png)

**Comment by fatimahyderi** [comment]
issue schecked

**Comment by wickywaka** [comment]
any update on this?

**Comment by fatimahyderi** [comment]
Assalam o alaikum
Hru?

I was not feeling well for last few days but insha'Allah I will do it as
soon as possible.

**Comment by wickywaka** [comment]
W Salam. No problem. Just keep me updated when you work on this.

**Comment by fatimahyderi** [comment]
If you are free we can do meeting on Sat ? I want to learn more abt git hub issues.

**Comment by fatimahyderi** [comment]
Sorry for delay.

**Comment by wickywaka** [comment]
> If you are free we can do meeting on Sat ? I want to learn more abt git hub issues.

If you have checked out this branch then just make a commit with your changes and push it. It will get uploaded here and then I can have a look at it.

**Comment by wickywaka** [comment]
Nice that you have already pushed the commit. Two things:

1. Instead showing all the LEDs inside the single component, we can have a single component show only one LED with a name and then use that component three times to show three LEDs.

2. Also we have to pull some changes from the main branch that are not updated in this branch.

Please let me know here if you have questions.

**Comment by fatimahyderi** [comment]
Ok, will do that.

**Comment by wickywaka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Web Application revision 1](https://trello.com/c/c5bWAkN8/3-web-application-revision-1)
